### ISSUE TITLE
这些菜单按钮怎么设置一直显示,?

### ISSUE THREAD

**Issue by 834116404** [chenshinshi/OneNote#1]
![image](https://github.com/chenshinshi/OneNote/assets/36099756/a0ef14fe-2d5e-405e-8db0-2a9e4bbc3525)
这些菜单怎么设置一直显示,?

目前是鼠标只要一移出来,就隐藏这些菜单按钮了, 我想即使鼠标挪出来,也显示这些菜单按钮,请问这个该怎么设置.

**Comment by chenshinshi** [comment]
#toolbar *{opacity:1 !important;}
