### ISSUE TITLE
思源3.1.10出现的布局样式bug

### ISSUE THREAD

**Issue by CHENPrime-coder** [chenshinshi/OneNote#10]
checkbox组件的小圆点飞走了，如图：

![err](https://github.com/user-attachments/assets/6b44e863-3653-45ce-8485-da57dd50f22d)

**Comment by chenshinshi** [comment]
是这样的，近期思源新版本导致这里的样式全部失效了，我晚上更新下

CHEN Prime ***@***.***> 於 2024年11月4日 週一 下午3:20寫道：
