### ISSUE TITLE
公式编辑器里的字会连字

### ISSUE THREAD

**Issue by lucianosimon399** [chenshinshi/OneNote#2]
![图片](https://github.com/chenshinshi/OneNote/assets/20676118/bb5238ae-ac48-474e-9396-07a795226eb0)
比如`(5)`会被显示为⑤，看论坛说是字体问题

**Comment by chenshinshi** [comment]
你好，请问使用自定义字型插件可否覆盖公式字体解决你的问题？

**Comment by lucianosimon399** [comment]
> 你好，请问使用自定义字型插件可否覆盖公式字体解决你的问题？

我直接用开发者工具改了字体，是能解决问题的

![图片](https://github.com/chenshinshi/OneNote/assets/20676118/69fcfb5d-5811-45a0-a6ae-5b739dc46305)

我在把b3-font-family改成了YaHei Monaco Hybird
