### ISSUE TITLE
windows客户端，显示问题

### ISSUE THREAD

**Issue by RogerHuHu** [chenshinshi/OneNote#3]
系统：windows 11
思源版本：2.10.6
主题版本已经最新了

1. 文档数显示样式与截图不一致（**这个问题不大**）
![问题1](https://github.com/chenshinshi/OneNote/assets/3404169/f40a83b1-7341-406c-bba1-b840e9087e57)

2. 上方文档标签页显示有问题（**这个影响比较大**）
 ![问题2](https://github.com/chenshinshi/OneNote/assets/3404169/2fffa538-7448-4e8a-9492-353ae9b45cf7)

**Comment by chenshinshi** [comment]
你好，是windows桌面版本吗？我这边无法复现。

Roger ***@***.***> 於 2023年9月26日 週二 下午12:54寫道：

**Comment by chenshinshi** [comment]
你是不是在qq群里绿色头像白兔子那位？手机浏览器小窗口这种我也不知道咋复现

Zone Carlton ***@***.***> 於 2023年9月26日 週二 下午12:55寫道：

**Comment by chenshinshi** [comment]
咋回事，我这边无法复现
