### ISSUE TITLE
0.23版本代码块行号错乱

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [chenshinshi/OneNote#5]
在cliff-drak出现代码块行号错乱之后，测试主题过程中发现Onenote主题的代码块行号也显示错误了，里面的内容还显示不全，顺便发现链滴上面有人把这个问题当成思源问题报了，没有报到主题这边，[链接](https://ld246.com/article/1698804597714)
#### 屏幕截图
![image](https://github.com/chenshinshi/OneNote/assets/61617417/93a31ac4-023d-4b89-b65b-0e83df7b55bc)

**Comment by qh0814** [comment]
我也有同样的问题。思源2.10.13版本，已经禁用代码片段和其他插件，主题在默认情况下就会这样。

**Comment by chenshinshi** [comment]
收到，近期会处理。
