### ISSUE TITLE
能否考虑增加类似浏览器的标签栏模式，以能够实现文档的二维快速选择

### ISSUE THREAD

**Issue by pisceswb** [chenshinshi/OneNote#6]
在文档树方面，请问作者能否开发一个类似浏览器的标签栏模式，以能够实现文档的二维的横向和纵向都能选择的文档树模式。横向列出所有笔记本（横向显示内容更多），点击打开后，能够显示该笔记本中的所有文档（包含子文档）。这将会比当前文档树模式仅能一维纵向选择文档方便的多。个人认为这也是onenote最出彩的地方，能够快速选择找到想要的文档
![image](https://github.com/chenshinshi/OneNote/assets/104658457/d5ac9e74-62d3-4d2f-97e0-0263e140a6af)

**Comment by chenshinshi** [comment]
您试过社区中的伪文档面包屑样式了吗？
